### ISSUE TITLE
Allow specifying toolbar GUID and cmdid at creation

### ISSUE THREAD

**Issue by zooba** [dotnet/interactive-window#14]
VS has a bug where toolbars (as identified by GUID/cmdid) appearing in multiple tool windows will share some visibility state for their icons. This results in icons added to the Python interactive appearing in the C# interactive:

![image](https://cloud.githubusercontent.com/assets/1693688/19734752/91ba4204-9b5d-11e6-8ba4-e54e6144e7dd.png)

VSPlat has acknowledged and wontfix'd the bug (you can also see it affect Solution Explorer if you open a second instance), and the best workaround for us is to have each user of the window provide their own toolbar.

**Comment by zooba** [comment]
For thoroughness, we've tried adding groups to the toolbar (doesn't work), adding extra toolbars via the host (they stack vertically, not horizontally), and DynamicVisibility (obviously necessary and leads to the issue as described - leaving it out clearly doesn't help).

We're happy to add the extension point, but would appreciate some API design guidance:
* should we add a new function to `IVsInteractiveWindowFactory` or would you prefer an `IVsInteractiveWindowFactory2`?
* would you prefer more parameters or an "options" object that can be extended later
 * is the factory interface COM visible? I think that would restrict the possibilities...
* what about a `CreateDeferred` method that allows setting properties before the call to `CreateToolWindow` occurs?

Pinging interested parties: @tmat @dinov @MikhailArkhipov

**Comment by MikhailArkhipov** [comment]
Implemented via `IVsInteractiveWindowFactory2` providing new `IVsInteractiveWindowDecorator`

**Comment by MikhailArkhipov** [comment]
https://github.com/dotnet/interactive-window/pull/23
