### ISSUE TITLE
2.3.0 depends on VS assemblies that don't exist

### ISSUE THREAD

**Issue by MikhailArkhipov** [dotnet/interactive-window#70]
```
Microsoft.VisualStudio.VsInteractiveWindow 2.3.0 depends on 
Microsoft.VisualStudio.Editor (>= 15.0.26201-alpha) but 
Microsoft.VisualStudio.Editor 15.0.26201-alpha was not found. 
An approximate best match of Microsoft.VisualStudio.Editor 15.0.26201 was resolved.
```

ditto others like

```
Microsoft.VisualStudio.VsInteractiveWindow 2.3.0 depends on
Microsoft.VisualStudio.ComponentModelHost (>= 15.0.26201-alpha)
```

**Comment by tmat** [comment]
Odd. The packages are available from myget: https://dotnet.myget.org/feed/roslyn-tools/package/nuget/Microsoft.VisualStudio.Editor/15.0.26201-alpha

The CI works fine. Just passed PR: https://github.com/dotnet/interactive-window/pull/71

**Comment by MikhailArkhipov** [comment]
This 2.3.0 is from nuget, not myget

**Comment by tmat** [comment]
Oh, I see.

**Comment by MikhailArkhipov** [comment]
Also, it depends on

``` 
<dependency id="Microsoft.VisualStudio.Text.Internal" version="15.0.26201-alpha" exclude="Build,Analyzers" />
```

and `Microsoft.VisualStudio.Text.Internal` is not published on nuget.

**Comment by tmat** [comment]
I see what happened - we didn't pass ```/warnaserror``` to msbuild and nuget only reports warnings when the dependencies are pre-release. I have added ```/warnaserror``` so that we catch it in microbuild next time.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/interactive-window/pull/72.

I have replaced the 2.3.0 packages on MyGet. Please clean up your nuget cache if you already installed them. Let me know if they work well and I'll upload them to NuGet.

**Comment by MikhailArkhipov** [comment]
So the one from **nuget.org** is not to be used?

**Comment by tmat** [comment]
https://dotnet.myget.org/gallery/interactive-window

**Comment by MikhailArkhipov** [comment]
OK, seems to be clean now :-) Thanks!
