### ISSUE TITLE
[Narrator+Edge] Narrator reads current window domain when expanding the select element in Edge

### ISSUE THREAD

**Issue by lildare** [dotnet/interactive-window#75]
1. Open html with any <select> element inside
2. Launch narrator
3. Expand select's options (Alt+key down or mouse click)

**Actual result:**
Narrator announces URL within option text when opening

**Expected result:**
Narrator reads only option's text

**Comment by tmat** [comment]
@lildare This repository hosts code and issues of Visual Studio Interactive Window. It's in no way related to Edge. Please open the bug on Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
